[package]
name = "kode-bridge"
authors = ["Tunglies"]
version = "0.1.4"
edition = "2024"
description = "Cross-platform Rust library for sending HTTP requests over IPC channels (Unix sockets, planned Windows named pipes)."
license = "Apache-2.0"
repository = "https://github.com/KodeBarinn/kode-bridge"
readme = "README.md"

[dependencies]
interprocess = { version = "2", features = ["tokio"] }
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["io-util"] }
futures = "0.3"
thiserror = "2"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }

[dev-dependencies]
dotenv = "0.15.0"
env = "1.0.1"
criterion = {version = "0.6.0", features = ["async"]}
async-trait = "0.1.88"

[[example]]
name = "request"
path = "examples/request.rs"

[[example]]
name = "request_large"
path = "examples/request_large.rs"

[[bench]]
name = "bench_version"
path = "benches/bench_version.rs"
harness = false

